services:
  db:
    container_name: database
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQl_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - "./db:/docker-entrypoint-initdb.d" # Thêm dòng này để mount thư mục db chứa các script
  web:
    container_name: web_app
    image: web
    build:
      context: web
    ports:
      - 8080:8080
    volumes:
      - ./log/:/app/log/
    depends_on:
      - db
    restart: on-failure
    environment:
      spring.datasource.url: "jdbc:mysql://database:3306/petclinic"
